<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Normalizer;

use Bitly\Runtime\Normalizer\CheckArray;
use Bitly\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class BulkUpdateRequestNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Bitly\Model\BulkUpdateRequest::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Bitly\Model\BulkUpdateRequest::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Bitly\Model\BulkUpdateRequest();
        if (\array_key_exists('archive', $data) && \is_int($data['archive'])) {
            $data['archive'] = (bool) $data['archive'];
        }
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('action', $data)) {
            $object->setAction($data['action']);
            unset($data['action']);
        }
        if (\array_key_exists('archive', $data)) {
            $object->setArchive($data['archive']);
            unset($data['archive']);
        }
        if (\array_key_exists('add_tags', $data)) {
            $values = [];
            foreach ($data['add_tags'] as $value) {
                $values[] = $value;
            }
            $object->setAddTags($values);
            unset($data['add_tags']);
        }
        if (\array_key_exists('remove_tags', $data)) {
            $values_1 = [];
            foreach ($data['remove_tags'] as $value_1) {
                $values_1[] = $value_1;
            }
            $object->setRemoveTags($values_1);
            unset($data['remove_tags']);
        }
        if (\array_key_exists('links', $data)) {
            $values_2 = [];
            foreach ($data['links'] as $value_2) {
                $values_2[] = $value_2;
            }
            $object->setLinks($values_2);
            unset($data['links']);
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_3;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        $dataArray['action'] = $data->getAction();
        if ($data->isInitialized('archive') && null !== $data->getArchive()) {
            $dataArray['archive'] = $data->getArchive();
        }
        if ($data->isInitialized('addTags') && null !== $data->getAddTags()) {
            $values = [];
            foreach ($data->getAddTags() as $value) {
                $values[] = $value;
            }
            $dataArray['add_tags'] = $values;
        }
        if ($data->isInitialized('removeTags') && null !== $data->getRemoveTags()) {
            $values_1 = [];
            foreach ($data->getRemoveTags() as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['remove_tags'] = $values_1;
        }
        if ($data->isInitialized('links') && null !== $data->getLinks()) {
            $values_2 = [];
            foreach ($data->getLinks() as $value_2) {
                $values_2[] = $value_2;
            }
            $dataArray['links'] = $values_2;
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value_3;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Bitly\Model\BulkUpdateRequest::class => false];
    }
}
