<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Normalizer;

use Bitly\Runtime\Normalizer\CheckArray;
use Bitly\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class BulkAddResponseDataNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Bitly\Model\BulkAddResponseData::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Bitly\Model\BulkAddResponseData::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Bitly\Model\BulkAddResponseData();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('successes', $data)) {
            $object->setSuccesses($data['successes']);
            unset($data['successes']);
        }
        if (\array_key_exists('csv_format_failures', $data)) {
            $object->setCsvFormatFailures($data['csv_format_failures']);
            unset($data['csv_format_failures']);
        }
        if (\array_key_exists('link_save_failures', $data)) {
            $object->setLinkSaveFailures($data['link_save_failures']);
            unset($data['link_save_failures']);
        }
        if (\array_key_exists('keyword_failures', $data)) {
            $object->setKeywordFailures($data['keyword_failures']);
            unset($data['keyword_failures']);
        }
        if (\array_key_exists('channel_bitlink_failures', $data)) {
            $object->setChannelBitlinkFailures($data['channel_bitlink_failures']);
            unset($data['channel_bitlink_failures']);
        }
        if (\array_key_exists('results', $data)) {
            $values = [];
            foreach ($data['results'] as $value) {
                $values[] = $value;
            }
            $object->setResults($values);
            unset($data['results']);
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_1;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('successes') && null !== $data->getSuccesses()) {
            $dataArray['successes'] = $data->getSuccesses();
        }
        if ($data->isInitialized('csvFormatFailures') && null !== $data->getCsvFormatFailures()) {
            $dataArray['csv_format_failures'] = $data->getCsvFormatFailures();
        }
        if ($data->isInitialized('linkSaveFailures') && null !== $data->getLinkSaveFailures()) {
            $dataArray['link_save_failures'] = $data->getLinkSaveFailures();
        }
        if ($data->isInitialized('keywordFailures') && null !== $data->getKeywordFailures()) {
            $dataArray['keyword_failures'] = $data->getKeywordFailures();
        }
        if ($data->isInitialized('channelBitlinkFailures') && null !== $data->getChannelBitlinkFailures()) {
            $dataArray['channel_bitlink_failures'] = $data->getChannelBitlinkFailures();
        }
        if ($data->isInitialized('results') && null !== $data->getResults()) {
            $values = [];
            foreach ($data->getResults() as $value) {
                $values[] = $value;
            }
            $dataArray['results'] = $values;
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value_1;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Bitly\Model\BulkAddResponseData::class => false];
    }
}
