<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Normalizer;

use Bitly\Runtime\Normalizer\CheckArray;
use Bitly\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CityDownloadMetricNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\CityDownloadMetric::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\CityDownloadMetric::class;
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\CityDownloadMetric();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('downloads', $data)) {
                $object->setDownloads($data['downloads']);
                unset($data['downloads']);
            }
            if (\array_key_exists('region', $data)) {
                $object->setRegion($data['region']);
                unset($data['region']);
            }
            if (\array_key_exists('subregion', $data)) {
                $object->setSubregion($data['subregion']);
                unset($data['subregion']);
            }
            if (\array_key_exists('city', $data)) {
                $object->setCity($data['city']);
                unset($data['city']);
            }
            if (\array_key_exists('coutry', $data)) {
                $object->setCoutry($data['coutry']);
                unset($data['coutry']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('downloads') && null !== $object->getDownloads()) {
                $data['downloads'] = $object->getDownloads();
            }
            if ($object->isInitialized('region') && null !== $object->getRegion()) {
                $data['region'] = $object->getRegion();
            }
            if ($object->isInitialized('subregion') && null !== $object->getSubregion()) {
                $data['subregion'] = $object->getSubregion();
            }
            if ($object->isInitialized('city') && null !== $object->getCity()) {
                $data['city'] = $object->getCity();
            }
            if ($object->isInitialized('coutry') && null !== $object->getCoutry()) {
                $data['coutry'] = $object->getCoutry();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\CityDownloadMetric::class => false];
        }
    }
} else {
    class CityDownloadMetricNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\CityDownloadMetric::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\CityDownloadMetric::class;
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\CityDownloadMetric();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('downloads', $data)) {
                $object->setDownloads($data['downloads']);
                unset($data['downloads']);
            }
            if (\array_key_exists('region', $data)) {
                $object->setRegion($data['region']);
                unset($data['region']);
            }
            if (\array_key_exists('subregion', $data)) {
                $object->setSubregion($data['subregion']);
                unset($data['subregion']);
            }
            if (\array_key_exists('city', $data)) {
                $object->setCity($data['city']);
                unset($data['city']);
            }
            if (\array_key_exists('coutry', $data)) {
                $object->setCoutry($data['coutry']);
                unset($data['coutry']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('downloads') && null !== $object->getDownloads()) {
                $data['downloads'] = $object->getDownloads();
            }
            if ($object->isInitialized('region') && null !== $object->getRegion()) {
                $data['region'] = $object->getRegion();
            }
            if ($object->isInitialized('subregion') && null !== $object->getSubregion()) {
                $data['subregion'] = $object->getSubregion();
            }
            if ($object->isInitialized('city') && null !== $object->getCity()) {
                $data['city'] = $object->getCity();
            }
            if ($object->isInitialized('coutry') && null !== $object->getCoutry()) {
                $data['coutry'] = $object->getCoutry();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\CityDownloadMetric::class => false];
        }
    }
}
