<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Normalizer;

use Bitly\Runtime\Normalizer\CheckArray;
use Bitly\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class DomainUpdateNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\DomainUpdate::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\DomainUpdate::class;
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\DomainUpdate();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('root_redirect', $data)) {
                $object->setRootRedirect($data['root_redirect']);
                unset($data['root_redirect']);
            }
            if (\array_key_exists('wildcard_redirect', $data)) {
                $object->setWildcardRedirect($data['wildcard_redirect']);
                unset($data['wildcard_redirect']);
            }
            if (\array_key_exists('https_enabled', $data)) {
                $object->setHttpsEnabled($data['https_enabled']);
                unset($data['https_enabled']);
            }
            if (\array_key_exists('hsts_enabled', $data)) {
                $object->setHstsEnabled($data['hsts_enabled']);
                unset($data['hsts_enabled']);
            }
            if (\array_key_exists('upgrade_insecure_requests', $data)) {
                $object->setUpgradeInsecureRequests($data['upgrade_insecure_requests']);
                unset($data['upgrade_insecure_requests']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('rootRedirect') && null !== $object->getRootRedirect()) {
                $data['root_redirect'] = $object->getRootRedirect();
            }
            if ($object->isInitialized('wildcardRedirect') && null !== $object->getWildcardRedirect()) {
                $data['wildcard_redirect'] = $object->getWildcardRedirect();
            }
            if ($object->isInitialized('httpsEnabled') && null !== $object->getHttpsEnabled()) {
                $data['https_enabled'] = $object->getHttpsEnabled();
            }
            if ($object->isInitialized('hstsEnabled') && null !== $object->getHstsEnabled()) {
                $data['hsts_enabled'] = $object->getHstsEnabled();
            }
            if ($object->isInitialized('upgradeInsecureRequests') && null !== $object->getUpgradeInsecureRequests()) {
                $data['upgrade_insecure_requests'] = $object->getUpgradeInsecureRequests();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\DomainUpdate::class => false];
        }
    }
} else {
    class DomainUpdateNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\DomainUpdate::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\DomainUpdate::class;
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\DomainUpdate();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('root_redirect', $data)) {
                $object->setRootRedirect($data['root_redirect']);
                unset($data['root_redirect']);
            }
            if (\array_key_exists('wildcard_redirect', $data)) {
                $object->setWildcardRedirect($data['wildcard_redirect']);
                unset($data['wildcard_redirect']);
            }
            if (\array_key_exists('https_enabled', $data)) {
                $object->setHttpsEnabled($data['https_enabled']);
                unset($data['https_enabled']);
            }
            if (\array_key_exists('hsts_enabled', $data)) {
                $object->setHstsEnabled($data['hsts_enabled']);
                unset($data['hsts_enabled']);
            }
            if (\array_key_exists('upgrade_insecure_requests', $data)) {
                $object->setUpgradeInsecureRequests($data['upgrade_insecure_requests']);
                unset($data['upgrade_insecure_requests']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('rootRedirect') && null !== $object->getRootRedirect()) {
                $data['root_redirect'] = $object->getRootRedirect();
            }
            if ($object->isInitialized('wildcardRedirect') && null !== $object->getWildcardRedirect()) {
                $data['wildcard_redirect'] = $object->getWildcardRedirect();
            }
            if ($object->isInitialized('httpsEnabled') && null !== $object->getHttpsEnabled()) {
                $data['https_enabled'] = $object->getHttpsEnabled();
            }
            if ($object->isInitialized('hstsEnabled') && null !== $object->getHstsEnabled()) {
                $data['hsts_enabled'] = $object->getHstsEnabled();
            }
            if ($object->isInitialized('upgradeInsecureRequests') && null !== $object->getUpgradeInsecureRequests()) {
                $data['upgrade_insecure_requests'] = $object->getUpgradeInsecureRequests();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\DomainUpdate::class => false];
        }
    }
}
