<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Normalizer;

use Bitly\Runtime\Normalizer\CheckArray;
use Bitly\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class FormCapturePayloadNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\FormCapturePayload::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\FormCapturePayload::class;
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\FormCapturePayload();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('name', $data)) {
                $object->setName($data['name']);
                unset($data['name']);
            }
            if (\array_key_exists('version', $data)) {
                $object->setVersion($data['version']);
                unset($data['version']);
            }
            if (\array_key_exists('submit_text', $data)) {
                $object->setSubmitText($data['submit_text']);
                unset($data['submit_text']);
            }
            if (\array_key_exists('skip_text', $data)) {
                $object->setSkipText($data['skip_text']);
                unset($data['skip_text']);
            }
            if (\array_key_exists('login', $data)) {
                $object->setLogin($data['login']);
                unset($data['login']);
            }
            if (\array_key_exists('org_guid', $data)) {
                $object->setOrgGuid($data['org_guid']);
                unset($data['org_guid']);
            }
            if (\array_key_exists('group_guid', $data)) {
                $object->setGroupGuid($data['group_guid']);
                unset($data['group_guid']);
            }
            if (\array_key_exists('response_status', $data)) {
                $object->setResponseStatus($data['response_status']);
                unset($data['response_status']);
            }
            if (\array_key_exists('pages', $data)) {
                $values = [];
                foreach ($data['pages'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, \Bitly\Model\FormPage::class, 'json', $context);
                }
                $object->setPages($values);
                unset($data['pages']);
            }
            foreach ($data as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_1;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('name') && null !== $object->getName()) {
                $data['name'] = $object->getName();
            }
            if ($object->isInitialized('version') && null !== $object->getVersion()) {
                $data['version'] = $object->getVersion();
            }
            if ($object->isInitialized('submitText') && null !== $object->getSubmitText()) {
                $data['submit_text'] = $object->getSubmitText();
            }
            if ($object->isInitialized('skipText') && null !== $object->getSkipText()) {
                $data['skip_text'] = $object->getSkipText();
            }
            if ($object->isInitialized('login') && null !== $object->getLogin()) {
                $data['login'] = $object->getLogin();
            }
            if ($object->isInitialized('orgGuid') && null !== $object->getOrgGuid()) {
                $data['org_guid'] = $object->getOrgGuid();
            }
            if ($object->isInitialized('groupGuid') && null !== $object->getGroupGuid()) {
                $data['group_guid'] = $object->getGroupGuid();
            }
            if ($object->isInitialized('responseStatus') && null !== $object->getResponseStatus()) {
                $data['response_status'] = $object->getResponseStatus();
            }
            if ($object->isInitialized('pages') && null !== $object->getPages()) {
                $values = [];
                foreach ($object->getPages() as $value) {
                    $values[] = $this->normalizer->normalize($value, 'json', $context);
                }
                $data['pages'] = $values;
            }
            foreach ($object as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_1;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\FormCapturePayload::class => false];
        }
    }
} else {
    class FormCapturePayloadNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\FormCapturePayload::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\FormCapturePayload::class;
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\FormCapturePayload();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('name', $data)) {
                $object->setName($data['name']);
                unset($data['name']);
            }
            if (\array_key_exists('version', $data)) {
                $object->setVersion($data['version']);
                unset($data['version']);
            }
            if (\array_key_exists('submit_text', $data)) {
                $object->setSubmitText($data['submit_text']);
                unset($data['submit_text']);
            }
            if (\array_key_exists('skip_text', $data)) {
                $object->setSkipText($data['skip_text']);
                unset($data['skip_text']);
            }
            if (\array_key_exists('login', $data)) {
                $object->setLogin($data['login']);
                unset($data['login']);
            }
            if (\array_key_exists('org_guid', $data)) {
                $object->setOrgGuid($data['org_guid']);
                unset($data['org_guid']);
            }
            if (\array_key_exists('group_guid', $data)) {
                $object->setGroupGuid($data['group_guid']);
                unset($data['group_guid']);
            }
            if (\array_key_exists('response_status', $data)) {
                $object->setResponseStatus($data['response_status']);
                unset($data['response_status']);
            }
            if (\array_key_exists('pages', $data)) {
                $values = [];
                foreach ($data['pages'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, \Bitly\Model\FormPage::class, 'json', $context);
                }
                $object->setPages($values);
                unset($data['pages']);
            }
            foreach ($data as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_1;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('name') && null !== $object->getName()) {
                $data['name'] = $object->getName();
            }
            if ($object->isInitialized('version') && null !== $object->getVersion()) {
                $data['version'] = $object->getVersion();
            }
            if ($object->isInitialized('submitText') && null !== $object->getSubmitText()) {
                $data['submit_text'] = $object->getSubmitText();
            }
            if ($object->isInitialized('skipText') && null !== $object->getSkipText()) {
                $data['skip_text'] = $object->getSkipText();
            }
            if ($object->isInitialized('login') && null !== $object->getLogin()) {
                $data['login'] = $object->getLogin();
            }
            if ($object->isInitialized('orgGuid') && null !== $object->getOrgGuid()) {
                $data['org_guid'] = $object->getOrgGuid();
            }
            if ($object->isInitialized('groupGuid') && null !== $object->getGroupGuid()) {
                $data['group_guid'] = $object->getGroupGuid();
            }
            if ($object->isInitialized('responseStatus') && null !== $object->getResponseStatus()) {
                $data['response_status'] = $object->getResponseStatus();
            }
            if ($object->isInitialized('pages') && null !== $object->getPages()) {
                $values = [];
                foreach ($object->getPages() as $value) {
                    $values[] = $this->normalizer->normalize($value, 'json', $context);
                }
                $data['pages'] = $values;
            }
            foreach ($object as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_1;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\FormCapturePayload::class => false];
        }
    }
}
