<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Normalizer;

use Bitly\Runtime\Normalizer\CheckArray;
use Bitly\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class PaymentsNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\Payments::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\Payments::class;
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\Payments();
            if (\array_key_exists('payment_amount', $data) && \is_int($data['payment_amount'])) {
                $data['payment_amount'] = (float) $data['payment_amount'];
            }
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('payment_amount', $data)) {
                $object->setPaymentAmount($data['payment_amount']);
                unset($data['payment_amount']);
            }
            if (\array_key_exists('payment_date', $data)) {
                $object->setPaymentDate($data['payment_date']);
                unset($data['payment_date']);
            }
            if (\array_key_exists('payment_number', $data)) {
                $object->setPaymentNumber($data['payment_number']);
                unset($data['payment_number']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('paymentAmount') && null !== $object->getPaymentAmount()) {
                $data['payment_amount'] = $object->getPaymentAmount();
            }
            if ($object->isInitialized('paymentDate') && null !== $object->getPaymentDate()) {
                $data['payment_date'] = $object->getPaymentDate();
            }
            if ($object->isInitialized('paymentNumber') && null !== $object->getPaymentNumber()) {
                $data['payment_number'] = $object->getPaymentNumber();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\Payments::class => false];
        }
    }
} else {
    class PaymentsNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Bitly\Model\Payments::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \Bitly\Model\Payments::class;
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Bitly\Model\Payments();
            if (\array_key_exists('payment_amount', $data) && \is_int($data['payment_amount'])) {
                $data['payment_amount'] = (float) $data['payment_amount'];
            }
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('payment_amount', $data)) {
                $object->setPaymentAmount($data['payment_amount']);
                unset($data['payment_amount']);
            }
            if (\array_key_exists('payment_date', $data)) {
                $object->setPaymentDate($data['payment_date']);
                unset($data['payment_date']);
            }
            if (\array_key_exists('payment_number', $data)) {
                $object->setPaymentNumber($data['payment_number']);
                unset($data['payment_number']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('paymentAmount') && null !== $object->getPaymentAmount()) {
                $data['payment_amount'] = $object->getPaymentAmount();
            }
            if ($object->isInitialized('paymentDate') && null !== $object->getPaymentDate()) {
                $data['payment_date'] = $object->getPaymentDate();
            }
            if ($object->isInitialized('paymentNumber') && null !== $object->getPaymentNumber()) {
                $data['payment_number'] = $object->getPaymentNumber();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Bitly\Model\Payments::class => false];
        }
    }
}
