<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Endpoint;

class UpdateLaunchpadSocial extends \Bitly\Runtime\Client\BaseEndpoint implements \Bitly\Runtime\Client\Endpoint
{
    use \Bitly\Runtime\Client\EndpointTrait;
    protected $button_id;
    protected $launchpad_id;

    /**
     * Updates a provided social icon on a provided link launchpad.
     *
     * @param string $buttonId    A GUID for a Bitly Link Launchpad button
     * @param string $launchpadId A GUID for a Bitly Link Launchpad
     */
    public function __construct(string $buttonId, string $launchpadId, \Bitly\Model\LaunchpadSocialRequest $requestBody)
    {
        $this->button_id = $buttonId;
        $this->launchpad_id = $launchpadId;
        $this->body = $requestBody;
    }

    public function getMethod(): string
    {
        return 'PATCH';
    }

    public function getUri(): string
    {
        return str_replace(['{button_id}', '{launchpad_id}'], [$this->button_id, $this->launchpad_id], '/launchpads/{launchpad_id}/contents/social/{button_id}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        if ($this->body instanceof \Bitly\Model\LaunchpadSocialRequest) {
            return [['Content-Type' => ['application/json']], $serializer->serialize($this->body, 'json')];
        }

        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    /**
     * @return \Bitly\Model\LaunchpadSocial|null
     *
     * @throws \Bitly\Exception\UpdateLaunchpadSocialBadRequestException
     * @throws \Bitly\Exception\UpdateLaunchpadSocialForbiddenException
     * @throws \Bitly\Exception\UpdateLaunchpadSocialNotFoundException
     * @throws \Bitly\Exception\UpdateLaunchpadSocialInternalServerErrorException
     * @throws \Bitly\Exception\UpdateLaunchpadSocialServiceUnavailableException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (is_null($contentType) === false && (200 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            return $serializer->deserialize($body, 'Bitly\Model\LaunchpadSocial', 'json');
        }
        if (is_null($contentType) === false && (400 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \Bitly\Exception\UpdateLaunchpadSocialBadRequestException($serializer->deserialize($body, 'Bitly\Model\BadRequest', 'json'), $response);
        }
        if (is_null($contentType) === false && (403 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \Bitly\Exception\UpdateLaunchpadSocialForbiddenException($serializer->deserialize($body, 'Bitly\Model\Forbidden', 'json'), $response);
        }
        if (is_null($contentType) === false && (404 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \Bitly\Exception\UpdateLaunchpadSocialNotFoundException($serializer->deserialize($body, 'Bitly\Model\NotFound', 'json'), $response);
        }
        if (is_null($contentType) === false && (500 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \Bitly\Exception\UpdateLaunchpadSocialInternalServerErrorException($serializer->deserialize($body, 'Bitly\Model\InternalError', 'json'), $response);
        }
        if (is_null($contentType) === false && (503 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \Bitly\Exception\UpdateLaunchpadSocialServiceUnavailableException($serializer->deserialize($body, 'Bitly\Model\TemporarilyUnavailable', 'json'), $response);
        }
    }

    public function getAuthenticationScopes(): array
    {
        return ['bearerAuth'];
    }
}
