<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class ActivityLog extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $actionDescription;
    /**
     * @var string
     */
    protected $actionLogin;
    /**
     * ISO timestamp.
     *
     * @var string
     */
    protected $ts;
    /**
     * @var string
     */
    protected $user;
    /**
     * @var string
     */
    protected $action;
    /**
     * @var string
     */
    protected $orgGuid;
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $countryCode;
    /**
     * @var string
     */
    protected $region;
    /**
     * @var string
     */
    protected $subRegion;
    /**
     * @var string
     */
    protected $city;
    /**
     * @var string
     */
    protected $isp;
    /**
     * Indicates an action take by Bitly.
     *
     * @var bool
     */
    protected $bitlyAdmin;
    /**
     * @var array<string, string>
     */
    protected $metadata;

    public function getActionDescription(): string
    {
        return $this->actionDescription;
    }

    public function setActionDescription(string $actionDescription): self
    {
        $this->initialized['actionDescription'] = true;
        $this->actionDescription = $actionDescription;

        return $this;
    }

    public function getActionLogin(): string
    {
        return $this->actionLogin;
    }

    public function setActionLogin(string $actionLogin): self
    {
        $this->initialized['actionLogin'] = true;
        $this->actionLogin = $actionLogin;

        return $this;
    }

    /**
     * ISO timestamp.
     */
    public function getTs(): string
    {
        return $this->ts;
    }

    /**
     * ISO timestamp.
     */
    public function setTs(string $ts): self
    {
        $this->initialized['ts'] = true;
        $this->ts = $ts;

        return $this;
    }

    public function getUser(): string
    {
        return $this->user;
    }

    public function setUser(string $user): self
    {
        $this->initialized['user'] = true;
        $this->user = $user;

        return $this;
    }

    public function getAction(): string
    {
        return $this->action;
    }

    public function setAction(string $action): self
    {
        $this->initialized['action'] = true;
        $this->action = $action;

        return $this;
    }

    public function getOrgGuid(): string
    {
        return $this->orgGuid;
    }

    public function setOrgGuid(string $orgGuid): self
    {
        $this->initialized['orgGuid'] = true;
        $this->orgGuid = $orgGuid;

        return $this;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getCountryCode(): string
    {
        return $this->countryCode;
    }

    public function setCountryCode(string $countryCode): self
    {
        $this->initialized['countryCode'] = true;
        $this->countryCode = $countryCode;

        return $this;
    }

    public function getRegion(): string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->initialized['region'] = true;
        $this->region = $region;

        return $this;
    }

    public function getSubRegion(): string
    {
        return $this->subRegion;
    }

    public function setSubRegion(string $subRegion): self
    {
        $this->initialized['subRegion'] = true;
        $this->subRegion = $subRegion;

        return $this;
    }

    public function getCity(): string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->initialized['city'] = true;
        $this->city = $city;

        return $this;
    }

    public function getIsp(): string
    {
        return $this->isp;
    }

    public function setIsp(string $isp): self
    {
        $this->initialized['isp'] = true;
        $this->isp = $isp;

        return $this;
    }

    /**
     * Indicates an action take by Bitly.
     */
    public function getBitlyAdmin(): bool
    {
        return $this->bitlyAdmin;
    }

    /**
     * Indicates an action take by Bitly.
     */
    public function setBitlyAdmin(bool $bitlyAdmin): self
    {
        $this->initialized['bitlyAdmin'] = true;
        $this->bitlyAdmin = $bitlyAdmin;

        return $this;
    }

    /**
     * @return array<string, string>
     */
    public function getMetadata(): iterable
    {
        return $this->metadata;
    }

    /**
     * @param array<string, string> $metadata
     */
    public function setMetadata(iterable $metadata): self
    {
        $this->initialized['metadata'] = true;
        $this->metadata = $metadata;

        return $this;
    }
}
