<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class AddBitlinkResult extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $channelGuid;
    /**
     * @var string
     */
    protected $hash;
    /**
     * @var string
     */
    protected $longUrl;
    /**
     * @var string
     */
    protected $url;
    /**
     * @var string
     */
    protected $keywordLink;
    /**
     * @var string
     */
    protected $title;
    /**
     * @var bool
     */
    protected $newChannelBitlink;
    /**
     * @var int
     */
    protected $bitlinkCreatedTs;
    /**
     * @var string
     */
    protected $shortenLinkError;
    /**
     * @var string
     */
    protected $channelBitlinkError;
    /**
     * @var string
     */
    protected $otherLinkError;

    public function getChannelGuid(): string
    {
        return $this->channelGuid;
    }

    public function setChannelGuid(string $channelGuid): self
    {
        $this->initialized['channelGuid'] = true;
        $this->channelGuid = $channelGuid;

        return $this;
    }

    public function getHash(): string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->initialized['hash'] = true;
        $this->hash = $hash;

        return $this;
    }

    public function getLongUrl(): string
    {
        return $this->longUrl;
    }

    public function setLongUrl(string $longUrl): self
    {
        $this->initialized['longUrl'] = true;
        $this->longUrl = $longUrl;

        return $this;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->initialized['url'] = true;
        $this->url = $url;

        return $this;
    }

    public function getKeywordLink(): string
    {
        return $this->keywordLink;
    }

    public function setKeywordLink(string $keywordLink): self
    {
        $this->initialized['keywordLink'] = true;
        $this->keywordLink = $keywordLink;

        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->initialized['title'] = true;
        $this->title = $title;

        return $this;
    }

    public function getNewChannelBitlink(): bool
    {
        return $this->newChannelBitlink;
    }

    public function setNewChannelBitlink(bool $newChannelBitlink): self
    {
        $this->initialized['newChannelBitlink'] = true;
        $this->newChannelBitlink = $newChannelBitlink;

        return $this;
    }

    public function getBitlinkCreatedTs(): int
    {
        return $this->bitlinkCreatedTs;
    }

    public function setBitlinkCreatedTs(int $bitlinkCreatedTs): self
    {
        $this->initialized['bitlinkCreatedTs'] = true;
        $this->bitlinkCreatedTs = $bitlinkCreatedTs;

        return $this;
    }

    public function getShortenLinkError(): string
    {
        return $this->shortenLinkError;
    }

    public function setShortenLinkError(string $shortenLinkError): self
    {
        $this->initialized['shortenLinkError'] = true;
        $this->shortenLinkError = $shortenLinkError;

        return $this;
    }

    public function getChannelBitlinkError(): string
    {
        return $this->channelBitlinkError;
    }

    public function setChannelBitlinkError(string $channelBitlinkError): self
    {
        $this->initialized['channelBitlinkError'] = true;
        $this->channelBitlinkError = $channelBitlinkError;

        return $this;
    }

    public function getOtherLinkError(): string
    {
        return $this->otherLinkError;
    }

    public function setOtherLinkError(string $otherLinkError): self
    {
        $this->initialized['otherLinkError'] = true;
        $this->otherLinkError = $otherLinkError;

        return $this;
    }
}
