<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class BillingAccountID extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $billingAccountId;

    public function getBillingAccountId(): string
    {
        return $this->billingAccountId;
    }

    public function setBillingAccountId(string $billingAccountId): self
    {
        $this->initialized['billingAccountId'] = true;
        $this->billingAccountId = $billingAccountId;

        return $this;
    }
}
