<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class BitlinkContentResponse extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $bitlinkId;
    /**
     * @var string
     */
    protected $linkTitle;
    /**
     * @var string
     */
    protected $description;
    /**
     * @var bool
     */
    protected $isPinned;
    /**
     * @var string
     */
    protected $imageUrl;

    public function getBitlinkId(): string
    {
        return $this->bitlinkId;
    }

    public function setBitlinkId(string $bitlinkId): self
    {
        $this->initialized['bitlinkId'] = true;
        $this->bitlinkId = $bitlinkId;

        return $this;
    }

    public function getLinkTitle(): string
    {
        return $this->linkTitle;
    }

    public function setLinkTitle(string $linkTitle): self
    {
        $this->initialized['linkTitle'] = true;
        $this->linkTitle = $linkTitle;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->initialized['description'] = true;
        $this->description = $description;

        return $this;
    }

    public function getIsPinned(): bool
    {
        return $this->isPinned;
    }

    public function setIsPinned(bool $isPinned): self
    {
        $this->initialized['isPinned'] = true;
        $this->isPinned = $isPinned;

        return $this;
    }

    public function getImageUrl(): string
    {
        return $this->imageUrl;
    }

    public function setImageUrl(string $imageUrl): self
    {
        $this->initialized['imageUrl'] = true;
        $this->imageUrl = $imageUrl;

        return $this;
    }
}
