<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class BSDSearchResults extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var list<BSDSearchResult>
     */
    protected $results;
    /**
     * @var InputDomain
     */
    protected $inputDomain;

    /**
     * @return list<BSDSearchResult>
     */
    public function getResults(): array
    {
        return $this->results;
    }

    /**
     * @param list<BSDSearchResult> $results
     */
    public function setResults(array $results): self
    {
        $this->initialized['results'] = true;
        $this->results = $results;

        return $this;
    }

    public function getInputDomain(): InputDomain
    {
        return $this->inputDomain;
    }

    public function setInputDomain(InputDomain $inputDomain): self
    {
        $this->initialized['inputDomain'] = true;
        $this->inputDomain = $inputDomain;

        return $this;
    }
}
