<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class BulkAddQRCodeResponse extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $message;
    /**
     * @var int
     */
    protected $successes;
    /**
     * @var int
     */
    protected $csvFormatFailures;
    /**
     * @var int
     */
    protected $qrCodeSaveFailures;
    /**
     * @var int
     */
    protected $keywordFailures;

    public function getMessage(): string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->initialized['message'] = true;
        $this->message = $message;

        return $this;
    }

    public function getSuccesses(): int
    {
        return $this->successes;
    }

    public function setSuccesses(int $successes): self
    {
        $this->initialized['successes'] = true;
        $this->successes = $successes;

        return $this;
    }

    public function getCsvFormatFailures(): int
    {
        return $this->csvFormatFailures;
    }

    public function setCsvFormatFailures(int $csvFormatFailures): self
    {
        $this->initialized['csvFormatFailures'] = true;
        $this->csvFormatFailures = $csvFormatFailures;

        return $this;
    }

    public function getQrCodeSaveFailures(): int
    {
        return $this->qrCodeSaveFailures;
    }

    public function setQrCodeSaveFailures(int $qrCodeSaveFailures): self
    {
        $this->initialized['qrCodeSaveFailures'] = true;
        $this->qrCodeSaveFailures = $qrCodeSaveFailures;

        return $this;
    }

    public function getKeywordFailures(): int
    {
        return $this->keywordFailures;
    }

    public function setKeywordFailures(int $keywordFailures): self
    {
        $this->initialized['keywordFailures'] = true;
        $this->keywordFailures = $keywordFailures;

        return $this;
    }
}
