<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class Campaign extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var array<string, string>
     */
    protected $references;
    /**
     * @var string
     */
    protected $guid;
    /**
     * @var string
     */
    protected $groupGuid;
    /**
     * @var string
     */
    protected $createdBy;
    /**
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $description;
    /**
     * ISO timestamp.
     *
     * @var string
     */
    protected $created;
    /**
     * ISO timestamp.
     *
     * @var string
     */
    protected $modified;

    /**
     * @return array<string, string>
     */
    public function getReferences(): iterable
    {
        return $this->references;
    }

    /**
     * @param array<string, string> $references
     */
    public function setReferences(iterable $references): self
    {
        $this->initialized['references'] = true;
        $this->references = $references;

        return $this;
    }

    public function getGuid(): string
    {
        return $this->guid;
    }

    public function setGuid(string $guid): self
    {
        $this->initialized['guid'] = true;
        $this->guid = $guid;

        return $this;
    }

    public function getGroupGuid(): string
    {
        return $this->groupGuid;
    }

    public function setGroupGuid(string $groupGuid): self
    {
        $this->initialized['groupGuid'] = true;
        $this->groupGuid = $groupGuid;

        return $this;
    }

    public function getCreatedBy(): string
    {
        return $this->createdBy;
    }

    public function setCreatedBy(string $createdBy): self
    {
        $this->initialized['createdBy'] = true;
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->initialized['description'] = true;
        $this->description = $description;

        return $this;
    }

    /**
     * ISO timestamp.
     */
    public function getCreated(): string
    {
        return $this->created;
    }

    /**
     * ISO timestamp.
     */
    public function setCreated(string $created): self
    {
        $this->initialized['created'] = true;
        $this->created = $created;

        return $this;
    }

    /**
     * ISO timestamp.
     */
    public function getModified(): string
    {
        return $this->modified;
    }

    /**
     * ISO timestamp.
     */
    public function setModified(string $modified): self
    {
        $this->initialized['modified'] = true;
        $this->modified = $modified;

        return $this;
    }
}
