<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class CampaignChannels extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var list<CampaignChannel>
     */
    protected $channels;
    /**
     * @var int
     */
    protected $total;

    /**
     * @return list<CampaignChannel>
     */
    public function getChannels(): array
    {
        return $this->channels;
    }

    /**
     * @param list<CampaignChannel> $channels
     */
    public function setChannels(array $channels): self
    {
        $this->initialized['channels'] = true;
        $this->channels = $channels;

        return $this;
    }

    public function getTotal(): int
    {
        return $this->total;
    }

    public function setTotal(int $total): self
    {
        $this->initialized['total'] = true;
        $this->total = $total;

        return $this;
    }
}
