<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class ChannelBitlink extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $bitlinkId;
    /**
     * @var string
     */
    protected $campaignGuid;
    /**
     * @var string
     */
    protected $channelGuid;

    public function getBitlinkId(): string
    {
        return $this->bitlinkId;
    }

    public function setBitlinkId(string $bitlinkId): self
    {
        $this->initialized['bitlinkId'] = true;
        $this->bitlinkId = $bitlinkId;

        return $this;
    }

    public function getCampaignGuid(): string
    {
        return $this->campaignGuid;
    }

    public function setCampaignGuid(string $campaignGuid): self
    {
        $this->initialized['campaignGuid'] = true;
        $this->campaignGuid = $campaignGuid;

        return $this;
    }

    public function getChannelGuid(): string
    {
        return $this->channelGuid;
    }

    public function setChannelGuid(string $channelGuid): self
    {
        $this->initialized['channelGuid'] = true;
        $this->channelGuid = $channelGuid;

        return $this;
    }
}
