<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class Charges extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var float
     */
    protected $chargeAmount;
    /**
     * @var string
     */
    protected $chargeName;
    /**
     * @var string
     */
    protected $processingType;
    /**
     * @var float
     */
    protected $taxAmount;

    public function getChargeAmount(): float
    {
        return $this->chargeAmount;
    }

    public function setChargeAmount(float $chargeAmount): self
    {
        $this->initialized['chargeAmount'] = true;
        $this->chargeAmount = $chargeAmount;

        return $this;
    }

    public function getChargeName(): string
    {
        return $this->chargeName;
    }

    public function setChargeName(string $chargeName): self
    {
        $this->initialized['chargeName'] = true;
        $this->chargeName = $chargeName;

        return $this;
    }

    public function getProcessingType(): string
    {
        return $this->processingType;
    }

    public function setProcessingType(string $processingType): self
    {
        $this->initialized['processingType'] = true;
        $this->processingType = $processingType;

        return $this;
    }

    public function getTaxAmount(): float
    {
        return $this->taxAmount;
    }

    public function setTaxAmount(float $taxAmount): self
    {
        $this->initialized['taxAmount'] = true;
        $this->taxAmount = $taxAmount;

        return $this;
    }
}
