<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class CreateQRCodeFromUrlRequest extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $groupGuid;
    /**
     * The destination URL the QR should point to. Always use long_url or bitlink, not both.
     *
     * @var string
     */
    protected $longUrl;
    /**
     * The bitlink the QR should point to. Always use long_url or bitlink, not both.
     *
     * @var string
     */
    protected $bitlink;
    /**
     * The file format to be returned after creation. Call GET /v4/qrcodes/{qrcode id} to get the QR code in a different format after creation.
     *
     * @var string
     */
    protected $responseFormat = 'png';
    /**
     * Options for customizing a QR Code's appearance.
     *
     * @var QRCodeCustomizations
     */
    protected $renderCustomizations;

    public function getGroupGuid(): string
    {
        return $this->groupGuid;
    }

    public function setGroupGuid(string $groupGuid): self
    {
        $this->initialized['groupGuid'] = true;
        $this->groupGuid = $groupGuid;

        return $this;
    }

    /**
     * The destination URL the QR should point to. Always use long_url or bitlink, not both.
     */
    public function getLongUrl(): string
    {
        return $this->longUrl;
    }

    /**
     * The destination URL the QR should point to. Always use long_url or bitlink, not both.
     */
    public function setLongUrl(string $longUrl): self
    {
        $this->initialized['longUrl'] = true;
        $this->longUrl = $longUrl;

        return $this;
    }

    /**
     * The bitlink the QR should point to. Always use long_url or bitlink, not both.
     */
    public function getBitlink(): string
    {
        return $this->bitlink;
    }

    /**
     * The bitlink the QR should point to. Always use long_url or bitlink, not both.
     */
    public function setBitlink(string $bitlink): self
    {
        $this->initialized['bitlink'] = true;
        $this->bitlink = $bitlink;

        return $this;
    }

    /**
     * The file format to be returned after creation. Call GET /v4/qrcodes/{qrcode id} to get the QR code in a different format after creation.
     */
    public function getResponseFormat(): string
    {
        return $this->responseFormat;
    }

    /**
     * The file format to be returned after creation. Call GET /v4/qrcodes/{qrcode id} to get the QR code in a different format after creation.
     */
    public function setResponseFormat(string $responseFormat): self
    {
        $this->initialized['responseFormat'] = true;
        $this->responseFormat = $responseFormat;

        return $this;
    }

    /**
     * Options for customizing a QR Code's appearance.
     */
    public function getRenderCustomizations(): QRCodeCustomizations
    {
        return $this->renderCustomizations;
    }

    /**
     * Options for customizing a QR Code's appearance.
     */
    public function setRenderCustomizations(QRCodeCustomizations $renderCustomizations): self
    {
        $this->initialized['renderCustomizations'] = true;
        $this->renderCustomizations = $renderCustomizations;

        return $this;
    }
}
