<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class CreateSubscriptionResponse extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $object;
    /**
     * @var string
     */
    protected $customer;
    /**
     * @var string
     */
    protected $status;
    /**
     * @var CreateSubscriptionResponseLatestInvoice
     */
    protected $latestInvoice;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getObject(): string
    {
        return $this->object;
    }

    public function setObject(string $object): self
    {
        $this->initialized['object'] = true;
        $this->object = $object;

        return $this;
    }

    public function getCustomer(): string
    {
        return $this->customer;
    }

    public function setCustomer(string $customer): self
    {
        $this->initialized['customer'] = true;
        $this->customer = $customer;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;

        return $this;
    }

    public function getLatestInvoice(): CreateSubscriptionResponseLatestInvoice
    {
        return $this->latestInvoice;
    }

    public function setLatestInvoice(CreateSubscriptionResponseLatestInvoice $latestInvoice): self
    {
        $this->initialized['latestInvoice'] = true;
        $this->latestInvoice = $latestInvoice;

        return $this;
    }
}
