<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class GroupHistoricalUsageTotals extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * the group's guid.
     *
     * @var string
     */
    protected $groupGuid;
    /**
     * @var list<HistoricalUsageTotal>
     */
    protected $historicalUsageTotals;

    /**
     * the group's guid.
     */
    public function getGroupGuid(): string
    {
        return $this->groupGuid;
    }

    /**
     * the group's guid.
     */
    public function setGroupGuid(string $groupGuid): self
    {
        $this->initialized['groupGuid'] = true;
        $this->groupGuid = $groupGuid;

        return $this;
    }

    /**
     * @return list<HistoricalUsageTotal>
     */
    public function getHistoricalUsageTotals(): array
    {
        return $this->historicalUsageTotals;
    }

    /**
     * @param list<HistoricalUsageTotal> $historicalUsageTotals
     */
    public function setHistoricalUsageTotals(array $historicalUsageTotals): self
    {
        $this->initialized['historicalUsageTotals'] = true;
        $this->historicalUsageTotals = $historicalUsageTotals;

        return $this;
    }
}
