<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class Invitation extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $email;
    /**
     * @var string
     */
    protected $roleName;
    /**
     * @var list<array<string, mixed>>
     */
    protected $groups;
    /**
     * @var string
     */
    protected $created;
    /**
     * login of the user who sent the invitation.
     *
     * @var string
     */
    protected $invitedBy;

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->initialized['email'] = true;
        $this->email = $email;

        return $this;
    }

    public function getRoleName(): string
    {
        return $this->roleName;
    }

    public function setRoleName(string $roleName): self
    {
        $this->initialized['roleName'] = true;
        $this->roleName = $roleName;

        return $this;
    }

    /**
     * @return list<array<string, mixed>>
     */
    public function getGroups(): array
    {
        return $this->groups;
    }

    /**
     * @param list<array<string, mixed>> $groups
     */
    public function setGroups(array $groups): self
    {
        $this->initialized['groups'] = true;
        $this->groups = $groups;

        return $this;
    }

    public function getCreated(): string
    {
        return $this->created;
    }

    public function setCreated(string $created): self
    {
        $this->initialized['created'] = true;
        $this->created = $created;

        return $this;
    }

    /**
     * login of the user who sent the invitation.
     */
    public function getInvitedBy(): string
    {
        return $this->invitedBy;
    }

    /**
     * login of the user who sent the invitation.
     */
    public function setInvitedBy(string $invitedBy): self
    {
        $this->initialized['invitedBy'] = true;
        $this->invitedBy = $invitedBy;

        return $this;
    }
}
