<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class LinksReportRequestResponse extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $brandGuid;
    /**
     * @var list<LinksReportRequestResponseRowsItem>
     */
    protected $rows;

    public function getBrandGuid(): string
    {
        return $this->brandGuid;
    }

    public function setBrandGuid(string $brandGuid): self
    {
        $this->initialized['brandGuid'] = true;
        $this->brandGuid = $brandGuid;

        return $this;
    }

    /**
     * @return list<LinksReportRequestResponseRowsItem>
     */
    public function getRows(): array
    {
        return $this->rows;
    }

    /**
     * @param list<LinksReportRequestResponseRowsItem> $rows
     */
    public function setRows(array $rows): self
    {
        $this->initialized['rows'] = true;
        $this->rows = $rows;

        return $this;
    }
}
