<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class LinksReportRequestResponseRowsItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $bitlink;
    /**
     * @var int
     */
    protected $created;
    /**
     * @var string
     */
    protected $title;
    /**
     * @var string
     */
    protected $longUrl;
    /**
     * @var string
     */
    protected $status;
    /**
     * @var list<LinksReportRequestResponseRowsItemMetricsItem>
     */
    protected $metrics;

    public function getBitlink(): string
    {
        return $this->bitlink;
    }

    public function setBitlink(string $bitlink): self
    {
        $this->initialized['bitlink'] = true;
        $this->bitlink = $bitlink;

        return $this;
    }

    public function getCreated(): int
    {
        return $this->created;
    }

    public function setCreated(int $created): self
    {
        $this->initialized['created'] = true;
        $this->created = $created;

        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->initialized['title'] = true;
        $this->title = $title;

        return $this;
    }

    public function getLongUrl(): string
    {
        return $this->longUrl;
    }

    public function setLongUrl(string $longUrl): self
    {
        $this->initialized['longUrl'] = true;
        $this->longUrl = $longUrl;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;

        return $this;
    }

    /**
     * @return list<LinksReportRequestResponseRowsItemMetricsItem>
     */
    public function getMetrics(): array
    {
        return $this->metrics;
    }

    /**
     * @param list<LinksReportRequestResponseRowsItemMetricsItem> $metrics
     */
    public function setMetrics(array $metrics): self
    {
        $this->initialized['metrics'] = true;
        $this->metrics = $metrics;

        return $this;
    }
}
