<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class OtherMetrics extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int
     */
    protected $otherCityClicks;
    /**
     * @var int
     */
    protected $noCityClicks;

    public function getOtherCityClicks(): int
    {
        return $this->otherCityClicks;
    }

    public function setOtherCityClicks(int $otherCityClicks): self
    {
        $this->initialized['otherCityClicks'] = true;
        $this->otherCityClicks = $otherCityClicks;

        return $this;
    }

    public function getNoCityClicks(): int
    {
        return $this->noCityClicks;
    }

    public function setNoCityClicks(int $noCityClicks): self
    {
        $this->initialized['noCityClicks'] = true;
        $this->noCityClicks = $noCityClicks;

        return $this;
    }
}
