<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class PublicSSLCert extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $validEnd;
    /**
     * @var bool
     */
    protected $customCert;
    /**
     * @var string
     */
    protected $issuer;

    public function getValidEnd(): string
    {
        return $this->validEnd;
    }

    public function setValidEnd(string $validEnd): self
    {
        $this->initialized['validEnd'] = true;
        $this->validEnd = $validEnd;

        return $this;
    }

    public function getCustomCert(): bool
    {
        return $this->customCert;
    }

    public function setCustomCert(bool $customCert): self
    {
        $this->initialized['customCert'] = true;
        $this->customCert = $customCert;

        return $this;
    }

    public function getIssuer(): string
    {
        return $this->issuer;
    }

    public function setIssuer(string $issuer): self
    {
        $this->initialized['issuer'] = true;
        $this->issuer = $issuer;

        return $this;
    }
}
