<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class QRCodeHistory extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var list<array<string, mixed>>
     */
    protected $qrcHistory;
    /**
     * @var float
     */
    protected $totalCount;

    /**
     * @return list<array<string, mixed>>
     */
    public function getQrcHistory(): array
    {
        return $this->qrcHistory;
    }

    /**
     * @param list<array<string, mixed>> $qrcHistory
     */
    public function setQrcHistory(array $qrcHistory): self
    {
        $this->initialized['qrcHistory'] = true;
        $this->qrcHistory = $qrcHistory;

        return $this;
    }

    public function getTotalCount(): float
    {
        return $this->totalCount;
    }

    public function setTotalCount(float $totalCount): self
    {
        $this->initialized['totalCount'] = true;
        $this->totalCount = $totalCount;

        return $this;
    }
}
