<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class SiteLinkPerformance extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int
     */
    protected $total;
    /**
     * @var list<SiteClicks>
     */
    protected $linkClicks;
    /**
     * @var string
     */
    protected $performanceStart;
    /**
     * @var string
     */
    protected $performanceEnd;
    /**
     * @var int
     */
    protected $units;
    /**
     * @var string
     */
    protected $unit;
    /**
     * @var string
     */
    protected $unitReference;
    /**
     * @var SitesPagination
     */
    protected $page;

    public function getTotal(): int
    {
        return $this->total;
    }

    public function setTotal(int $total): self
    {
        $this->initialized['total'] = true;
        $this->total = $total;

        return $this;
    }

    /**
     * @return list<SiteClicks>
     */
    public function getLinkClicks(): array
    {
        return $this->linkClicks;
    }

    /**
     * @param list<SiteClicks> $linkClicks
     */
    public function setLinkClicks(array $linkClicks): self
    {
        $this->initialized['linkClicks'] = true;
        $this->linkClicks = $linkClicks;

        return $this;
    }

    public function getPerformanceStart(): string
    {
        return $this->performanceStart;
    }

    public function setPerformanceStart(string $performanceStart): self
    {
        $this->initialized['performanceStart'] = true;
        $this->performanceStart = $performanceStart;

        return $this;
    }

    public function getPerformanceEnd(): string
    {
        return $this->performanceEnd;
    }

    public function setPerformanceEnd(string $performanceEnd): self
    {
        $this->initialized['performanceEnd'] = true;
        $this->performanceEnd = $performanceEnd;

        return $this;
    }

    public function getUnits(): int
    {
        return $this->units;
    }

    public function setUnits(int $units): self
    {
        $this->initialized['units'] = true;
        $this->units = $units;

        return $this;
    }

    public function getUnit(): string
    {
        return $this->unit;
    }

    public function setUnit(string $unit): self
    {
        $this->initialized['unit'] = true;
        $this->unit = $unit;

        return $this;
    }

    public function getUnitReference(): string
    {
        return $this->unitReference;
    }

    public function setUnitReference(string $unitReference): self
    {
        $this->initialized['unitReference'] = true;
        $this->unitReference = $unitReference;

        return $this;
    }

    public function getPage(): SitesPagination
    {
        return $this->page;
    }

    public function setPage(SitesPagination $page): self
    {
        $this->initialized['page'] = true;
        $this->page = $page;

        return $this;
    }
}
