<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Bitly\Model;

class UpdateStripeCustomerBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Customer name.
     *
     * @var string
     */
    protected $name;
    /**
     * Customer phone number.
     *
     * @var string
     */
    protected $phone;
    /**
     * Customer email address.
     *
     * @var string
     */
    protected $email;
    /**
     * Customer company name.
     *
     * @var string
     */
    protected $companyName;
    /**
     * Customer tax ID.
     *
     * @var string
     */
    protected $taxId;
    /**
     * Customer description.
     *
     * @var string
     */
    protected $description;
    /**
     * @var StripeAddress
     */
    protected $taxAddress;
    /**
     * @var StripeAddress
     */
    protected $invoiceAddress;

    /**
     * Customer name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Customer name.
     */
    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    /**
     * Customer phone number.
     */
    public function getPhone(): string
    {
        return $this->phone;
    }

    /**
     * Customer phone number.
     */
    public function setPhone(string $phone): self
    {
        $this->initialized['phone'] = true;
        $this->phone = $phone;

        return $this;
    }

    /**
     * Customer email address.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Customer email address.
     */
    public function setEmail(string $email): self
    {
        $this->initialized['email'] = true;
        $this->email = $email;

        return $this;
    }

    /**
     * Customer company name.
     */
    public function getCompanyName(): string
    {
        return $this->companyName;
    }

    /**
     * Customer company name.
     */
    public function setCompanyName(string $companyName): self
    {
        $this->initialized['companyName'] = true;
        $this->companyName = $companyName;

        return $this;
    }

    /**
     * Customer tax ID.
     */
    public function getTaxId(): string
    {
        return $this->taxId;
    }

    /**
     * Customer tax ID.
     */
    public function setTaxId(string $taxId): self
    {
        $this->initialized['taxId'] = true;
        $this->taxId = $taxId;

        return $this;
    }

    /**
     * Customer description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Customer description.
     */
    public function setDescription(string $description): self
    {
        $this->initialized['description'] = true;
        $this->description = $description;

        return $this;
    }

    public function getTaxAddress(): StripeAddress
    {
        return $this->taxAddress;
    }

    public function setTaxAddress(StripeAddress $taxAddress): self
    {
        $this->initialized['taxAddress'] = true;
        $this->taxAddress = $taxAddress;

        return $this;
    }

    public function getInvoiceAddress(): StripeAddress
    {
        return $this->invoiceAddress;
    }

    public function setInvoiceAddress(StripeAddress $invoiceAddress): self
    {
        $this->initialized['invoiceAddress'] = true;
        $this->invoiceAddress = $invoiceAddress;

        return $this;
    }
}
